# permissions for end users to edit secretsrotationmappings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secretsrotationmapping-editor-role
rules:
- apiGroups:
  - awssecretsoperator.secretoperator
  resources:
  - secretsrotationmappings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - awssecretsoperator.secretoperator
  resources:
  - secretsrotationmappings/status
  verbs:
  - get
