# permissions for end users to view secretsrotationmappings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secretsrotationmapping-viewer-role
rules:
- apiGroups:
  - awssecretsoperator.secretoperator
  resources:
  - secretsrotationmappings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - awssecretsoperator.secretoperator
  resources:
  - secretsrotationmappings/status
  verbs:
  - get
