apiVersion: awssecretsoperator.secretoperator/v1
kind: SecretsRotationMapping
metadata:
  name: secretsrotationmapping-sample
spec:
  SecretID: "eks-controller-test-secret"
  Labels: 
    environment: operatortest